# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aefcdffa46e54143454471ef0a331c53eb377d03792d7320d647bbb9093913b716e6ca83b748008556b7cf64c24fa54e8d732446d1f2ecc485ec0bd211dbc23

test:
  secret_key_base: ee77f9316cfe71d9f95810ad30b51b6c7c9f34f7c705f7d26dfe610a5360f10508722b9c83d57828569c90c6f12be6546b049bba4e42ed70ca424a54e0591968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
